# Generated by Django 4.1 on 2022-08-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcap_users', '0002_account_date_joined_account_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
