# Generated by Django 4.1 on 2022-08-05 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcap_users', '0005_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcap_users.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcap_users.account')),
            ],
        ),
    ]
