# Generated by Django 4.1 on 2022-08-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcap_users', '0006_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='player1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player1_points',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player2_points',
        ),
        migrations.AddField(
            model_name='participant',
            name='player_points',
            field=models.FloatField(null=True),
        ),
    ]
