# Generated by Django 4.1 on 2022-08-06 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcap_users', '0007_remove_match_player1_remove_match_player1_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='totalPlayers',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fcap_users.account'),
        ),
    ]
