# Generated by Django 4.1 on 2022-08-06 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcap_users', '0008_match_totalplayers_match_winner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_time']},
        ),
    ]
