# Generated by Django 4.1 on 2022-08-07 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcap_users', '0010_participant_player_new_rankings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='player_new_rankings',
            new_name='player_new_ratings',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='player_prev_rankings',
            new_name='player_prev_ratings',
        ),
    ]
