# Generated by Django 4.1 on 2022-08-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcap_users', '0013_challenge_totalplayers'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge_participant',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
