# Generated by Django 4.1 on 2022-08-16 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcap_users', '0016_challenge_expiry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='challenge_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
